name: Automerge

on:
  push:
    branches:
      - develop

jobs:
    automerge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{github.token}}
          source: 'develop'
          target: 'main'