name: WriteConfig

on:
  push:
    branches:
      - develop

jobs:
  write-config:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: write
        run: |
          echo 'The message is: ${{ secrets.message }}' >> config.yml